import fs from 'node:fs';
import path from 'node:path';
import { escape as e, markdown, validURL, validatePost } from './lib.mjs';
const root = path.resolve(import.meta.dirname,'..');
const out = path.join(root,'dist');
const site = JSON.parse(fs.readFileSync(path.join(root,'content/site.json'),'utf8'));
const siteURL = (process.env.SITE_URL || site.site_url || '').replace(/\/$/,'');
if (siteURL && !validURL(siteURL)) throw Error('site_url 无效');
if (!validURL(site.cms_url)) throw Error('cms_url 无效');
const base = (process.env.BASE_PATH ?? (siteURL ? new URL(siteURL).pathname : '')).replace(/\/$/,'');
if (base && !/^\/[a-zA-Z0-9_\/-]+$/.test(base)) throw Error('BASE_PATH 无效');
const href = p => `${base}/${p}`;
const all = fs.readdirSync(path.join(root,'content/posts')).filter(f=>f.endsWith('.json')).map(f=>validatePost(JSON.parse(fs.readFileSync(path.join(root,'content/posts',f),'utf8'))));
if (new Set(all.map(p=>p.slug)).size !== all.length) throw Error('重复 slug');
const posts = all.filter(p=>p.published && p.date <= new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'})).sort((a,b)=>b.date.localeCompare(a.date) || a.slug.localeCompare(b.slug));
// Clear only the fixed generated directory inside this project.
if (out !== path.join(root,'dist')) throw Error('无效输出目录');
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
const write = (p,s) => {const file=path.join(out,p);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,s);};
const words = {
 zh:{home:'首页',ashares:'A 股研究',ai:'AI 与商业',about:'关于',subscribe:'订阅',all:'全部文章',reading:'阅读推荐',original:'原创研究',latest:'最近的阅读与思考',read:'阅读全文',source:'阅读原始资料 ↗',date:'本站发布',sourceDate:'原文发布',attribution:'导读由 AI 协助整理；这是阅读提示，不代表作者已形成个人投资判断。',search:'搜索文章标题与摘要',empty:'没有找到符合条件的文章。',footer:'海边的卡夫卡 · 记录证据、判断与修正',rss:'通过 RSS，慢慢读。',manage:'内容管理',label:'研究札记 / RESEARCH JOURNAL'},
 en:{home:'Home',ashares:'A-share Research',ai:'AI & Business',about:'About',subscribe:'Subscribe',all:'All articles',reading:'Reading list',original:'Original research',latest:'Recent reading & reflections',read:'Read article',source:'Read the primary source ↗',date:'Published here',sourceDate:'Source published',attribution:'This reading guide was prepared with AI assistance. It does not represent a personal investment conclusion by the author.',search:'Search titles and summaries',empty:'No articles match your search.',footer:'Kafka by the Sea · Evidence, ideas and revisions',rss:'A quieter way to keep up.',manage:'Content management',label:'RESEARCH JOURNAL / 海边的卡夫卡'}
};
const category = (p,l)=>p.category==='ai'?words[l].ai:words[l].ashares;
function frame(lang,route,title,description,body){
 const t=words[lang],other=lang==='zh'?'en':'zh',url=siteURL?`${siteURL}/${lang}/${route}`:'';
 const nav=[['',t.home],['a-shares/',t.ashares],['ai/',t.ai],['about/',t.about],['subscribe/',t.subscribe]];
 return `<!doctype html><html lang="${lang==='zh'?'zh-CN':'en'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${e(description)}"><meta name="referrer" content="no-referrer"><title>${e(title)} · ${e(site['name_'+lang])}</title>${url?`<link rel="canonical" href="${e(url)}"><link rel="alternate" hreflang="zh-CN" href="${e(siteURL+'/zh/'+route)}"><link rel="alternate" hreflang="en" href="${e(siteURL+'/en/'+route)}">`:''}<link rel="icon" href="${href('assets/favicon.svg')}" type="image/svg+xml"><link rel="stylesheet" href="${href('assets/style.css')}"><link rel="alternate" type="application/rss+xml" title="${e(site['name_'+lang])}" href="${href(lang+'/feed.xml')}"><script src="${href('assets/site.js')}" defer></script></head><body><a class="skip" href="#main">${lang==='zh'?'跳至内容':'Skip to content'}</a><header class="header"><a class="brand" href="${href(lang+'/')}"><span class="brand-mark" aria-hidden="true">≈</span><span>${e(site['name_'+lang])}<small>${lang==='zh'?'Kafka by the Sea':'海边的卡夫卡'}</small></span></a><nav aria-label="${lang==='zh'?'主导航':'Main navigation'}">${nav.map(([r,label])=>`<a ${r===route?'aria-current="page"':''} href="${href(lang+'/'+r)}">${label}</a>`).join('')}</nav><a class="language" href="${href(other+'/'+route)}" lang="${other}">${lang==='zh'?'EN ↗':'中文 ↗'}</a></header><main id="main">${body}</main><footer><span>${e(t.footer)}</span><div><a href="${href(lang+'/feed.xml')}">RSS</a><a href="${href('admin/')}">${t.manage}</a></div></footer></body></html>`;
}
function card(p,l,i){const t=words[l];return `<article class="post-card" data-search="${e((p['title_'+l]+' '+p['summary_'+l]).toLowerCase())}"><span class="post-index">${String(i+1).padStart(2,'0')}</span><div><div class="meta"><span>${category(p,l)}</span><span>${t[p.kind]}</span><time datetime="${p.date}">${p.date}</time></div><h3><a href="${href(l+'/posts/'+p.slug+'/')}">${e(p['title_'+l])}</a></h3><p>${e(p['summary_'+l])}</p></div><a class="card-arrow" aria-label="${e(t.read+': '+p['title_'+l])}" href="${href(l+'/posts/'+p.slug+'/')}">↗</a></article>`;}
function list(ps,l){return `<div class="search"><label for="search">${words[l].search}</label><input id="search" type="search" placeholder="${l==='zh'?'输入关键词，如现金流、AI…':'Try cash flow, AI…'}"></div><div class="post-list">${ps.map((p,i)=>card(p,l,i)).join('')}</div><p id="empty" hidden>${words[l].empty}</p>`;}
for(const l of ['zh','en']){
 const t=words[l];
 const art=`<div class="sea" role="img" aria-label="${l==='zh'?'抽象海岸线插画':'An abstract shoreline illustration'}"><div class="sun"></div><div class="horizon"></div><div class="water"></div><div class="shore"></div><span>THOUGHTS COME IN WAVES.</span></div>`;
 const hero=`<section class="hero"><div><p class="eyebrow">${t.label}</p><h1>${e(site['headline_'+l]).replace(/\n/g,'<br>')}</h1><p class="intro">${e(site['intro_'+l])}</p><a class="button" href="#articles">${l==='zh'?'从一篇文章开始':'Start with an article'} <span>↓</span></a><div class="hero-note">A-SHARES <span> / </span> AI & BUSINESS</div></div>${art}</section>`;
 const topics=`<section class="topics"><a href="${href(l+'/a-shares/')}"><span class="eyebrow">01 / A-SHARES</span><h2>${t.ashares} ↗</h2><p>${l==='zh'?'从公司披露出发，读懂利润背后的生意。':'Start with company disclosures. Understand the business behind the earnings.'}</p></a><a href="${href(l+'/ai/')}"><span class="eyebrow">02 / AI & BUSINESS</span><h2>${t.ai} ↗</h2><p>${l==='zh'?'沿着技术、使用与付费，寻找商业兑现的证据。':'Follow technology, adoption and payment to the evidence of commercial value.'}</p></a></section>`;
 write(l+'/index.html',frame(l,'',t.home,site['intro_'+l],hero+topics+`<section id="articles"><div class="section-title"><h2>${t.latest}</h2><span>${String(posts.length).padStart(2,'0')} ${l==='zh'?'篇文章':'ARTICLES'}</span></div>${list(posts,l)}</section>`));
 for(const c of ['a-shares','ai']){const label=c==='ai'?t.ai:t.ashares;write(l+'/'+c+'/index.html',frame(l,c+'/',label,label,`<section class="page-heading"><p class="eyebrow">${c==='ai'?'AI & BUSINESS':'A-SHARE RESEARCH'}</p><h1>${label}</h1><p>${l==='zh'?'把资料读透，让判断有据可查。':'Read the source. Make the reasoning traceable.'}</p></section>${list(posts.filter(p=>p.category===c),l)}`));}
 const about=`<section class="page-heading"><p class="eyebrow">ABOUT THIS JOURNAL</p><h1>${t.about}</h1></section><div class="prose"><h2>${e(site['name_'+l])}</h2><p>${e(site['intro_'+l])}</p><h2>${l==='zh'?'这里怎样写作':'How this journal is written'}</h2><p>${l==='zh'?'文章分为原创研究与阅读推荐。阅读推荐链接原始资料，本站导读与原作者正文分别署名。公司披露、分析推断与仍待验证的问题会在文中区分；资料的日期决定它所描述的时间范围。':'Articles are marked as original research or reading guides. Guides link to primary material and distinguish our commentary from the source. Company disclosures, interpretation and open questions are identified, with dates defining the period covered.'}</p><h2>${l==='zh'?'匿名与隐私':'Identity and privacy'}</h2><p>${l==='zh'?'这里使用笔名，不公开个人履历或联系方式。网站未接入访问分析、广告或评论，也不收集订阅邮箱。RSS 由读者自己的阅读器订阅；托管平台可能处理其正常运行所需的访问日志。':'This journal uses a pen name without personal background or contact details. There are no analytics, ads or comments, and no subscription email collection. RSS is handled by your reader; the hosting provider may process access logs needed to operate its service.'}</p></div>`;
 write(l+'/about/index.html',frame(l,'about/',t.about,t.about,about));
 write(l+'/subscribe/index.html',frame(l,'subscribe/',t.subscribe,t.rss,`<section class="page-heading"><p class="eyebrow">RSS / KEEP IN TOUCH</p><h1>${t.rss}</h1><p>${l==='zh'?'没有邮件列表。把订阅地址加入你习惯的 RSS 阅读器，新文章会在那里等你。':'No mailing list. Add a feed to your RSS reader and new articles will appear there.'}</p></section><div class="feed-grid">${['zh','en'].map(lang=>`<section class="feed-card"><h2>${lang==='zh'?'中文文章':'English articles'}</h2><a href="${href(lang+'/feed.xml')}">${lang==='zh'?'打开中文 RSS':'Open English RSS'} ↗</a><button class="copy-feed" data-path="${href(lang+'/feed.xml')}">${l==='zh'?'复制订阅地址':'Copy feed URL'}</button></section>`).join('')}</div><p class="subtle">${l==='zh'?'中英文为同一篇文章的两个版本，选择一个订阅即可避免重复。':'The feeds contain two language versions of the same articles. Choose one to avoid duplicates.'}</p><p id="copy-status" role="status"></p>`));
 for(const p of posts){const source=p.source_url?`<aside class="source"><span class="eyebrow">PRIMARY SOURCE</span><h2>${e(p.source_title)}</h2><p>${e(p.source_author)} · ${t.sourceDate} ${e(p.source_date)}</p><a href="${e(p.source_url)}" target="_blank" rel="noopener noreferrer">${t.source}</a></aside>`:'';const body=`<article><header class="article-heading"><a class="back" href="${href(l+'/'+p.category+'/')}">← ${category(p,l)}</a><div class="meta"><span>${t[p.kind]}</span><time datetime="${p.date}">${t.date} ${p.date}</time></div><h1>${e(p['title_'+l])}</h1><p class="dek">${e(p['summary_'+l])}</p><p class="attribution">${p.kind==='reading'?t.attribution:e(p['author_'+l] || site['name_'+l])}</p></header><div class="prose">${markdown(p['body_'+l])}${source}</div></article>`;write(l+'/posts/'+p.slug+'/index.html',frame(l,'posts/'+p.slug+'/',p['title_'+l],p['summary_'+l],body));}
 const feedBase=siteURL || 'http://127.0.0.1:4173'+base;
 write(l+'/feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>${e(site['name_'+l])}</title><link>${e(feedBase+'/'+l+'/')}</link><description>${e(site['intro_'+l])}</description><language>${l==='zh'?'zh-cn':'en'}</language><atom:link href="${e(feedBase+'/'+l+'/feed.xml')}" rel="self" type="application/rss+xml"/>${posts.map(p=>{const u=feedBase+'/'+l+'/posts/'+p.slug+'/';return `<item><title>${e(p['title_'+l])}</title><link>${e(u)}</link><guid>${e(u)}</guid><pubDate>${new Date(p.date+'T12:00:00+08:00').toUTCString()}</pubDate><description>${e(p['summary_'+l])}</description></item>`;}).join('')}</channel></rss>`);
}
write('index.html',`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0;url=${href('zh/')}"><title>${e(site.name_zh)}</title></head><body><a href="${href('zh/')}">进入中文主页</a> / <a href="${href('en/')}">English</a></body></html>`);
write('404.html',frame('zh','','页面未找到','页面未找到',`<section class="page-heading"><p class="eyebrow">404 / A DIFFERENT SHORE</p><h1>这一页暂时不在这里。</h1><a class="button" href="${href('zh/')}">返回首页 →</a></section>`));
write('.nojekyll','');
write('assets/posts.json',JSON.stringify(posts));
write('assets/site.json',JSON.stringify(site));
for(const f of fs.readdirSync(path.join(root,'public/assets')))write('assets/'+f,fs.readFileSync(path.join(root,'public/assets',f)));
write('admin/index.html',fs.readFileSync(path.join(root,'public/admin/index.html'),'utf8').replaceAll('__BASE__',base));
if(siteURL){const urls=['zh/','en/',...['zh','en'].flatMap(l=>['a-shares/','ai/','about/','subscribe/',...posts.map(p=>'posts/'+p.slug+'/')].map(r=>l+'/'+r))];write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${e(siteURL+'/'+u)}</loc></url>`).join('')}</urlset>`);write('robots.txt',`User-agent: *\nDisallow: ${base}/admin/\nSitemap: ${siteURL}/sitemap.xml\n`);}
console.log(`Built ${posts.length} bilingual articles → dist; base=${base || '/'}; ${siteURL?'production URLs':'local preview URLs'}`);
